/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.City;
import model.DoctorDirectory;
import model.HospitalDirectory;
import model.PatientDirectory;
import model.PersonDirectory;
import model.SystemClass;

/**
 *
 * @author Shubham Idekar
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonDirectory person;
    PatientDirectory ptDirectory;
    DoctorDirectory docDirectory;
    HospitalDirectory hospDirectory;
    City commDirectory;
    SystemClass sys;
    public MainJFrame() {
        initComponents();
        this.person = new PersonDirectory();
        this.ptDirectory = new PatientDirectory();
        this.docDirectory = new DoctorDirectory();
        this.hospDirectory = new HospitalDirectory();
        this.commDirectory = new City();
        this.sys = new SystemClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlArea = new javax.swing.JPanel();
        Systembtn = new javax.swing.JButton();
        Patientbtn = new javax.swing.JButton();
        Doctorbtn = new javax.swing.JButton();
        btnHospLogin = new javax.swing.JButton();
        btnCommLogin = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlArea.setBackground(new java.awt.Color(0, 153, 255));

        Systembtn.setText("System");
        Systembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystembtnActionPerformed(evt);
            }
        });

        Patientbtn.setText("Patient");
        Patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientbtnActionPerformed(evt);
            }
        });

        Doctorbtn.setText("Doctor");
        Doctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorbtnActionPerformed(evt);
            }
        });

        btnHospLogin.setText("Hospital");
        btnHospLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospLoginActionPerformed(evt);
            }
        });

        btnCommLogin.setText("Community");
        btnCommLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlAreaLayout = new javax.swing.GroupLayout(controlArea);
        controlArea.setLayout(controlAreaLayout);
        controlAreaLayout.setHorizontalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCommLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnHospLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Systembtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Doctorbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Patientbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlAreaLayout.setVerticalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Systembtn)
                .addGap(18, 18, 18)
                .addComponent(btnHospLogin)
                .addGap(18, 18, 18)
                .addComponent(btnCommLogin)
                .addGap(18, 18, 18)
                .addComponent(Doctorbtn)
                .addGap(18, 18, 18)
                .addComponent(Patientbtn)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlArea);

        workArea.setBackground(new java.awt.Color(102, 204, 255));
        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SystembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystembtnActionPerformed
        // TODO add your handling code here:
        SystemPanel syst = new SystemPanel(workArea, person, ptDirectory, docDirectory,hospDirectory, commDirectory, sys);
        workArea.add("SystemPanel",syst );
        CardLayout lay = (CardLayout) workArea.getLayout();
        lay.next(workArea);

    }//GEN-LAST:event_SystembtnActionPerformed

    private void DoctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorbtnActionPerformed
        // TODO add your handling code here:
        DoctorPanel doc = new DoctorPanel(workArea, person, ptDirectory, docDirectory,hospDirectory, commDirectory, sys);
        workArea.add("DoctorPanel",doc );
        CardLayout lay = (CardLayout) workArea.getLayout();
        lay.next(workArea);
    }//GEN-LAST:event_DoctorbtnActionPerformed

    private void PatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientbtnActionPerformed
        // TODO add your handling code here:
          PatientPanel panelpatient = new PatientPanel(workArea, person, ptDirectory, docDirectory,hospDirectory, commDirectory, sys);
          workArea.add("PatientPanel",panelpatient );
          CardLayout lay = (CardLayout) workArea.getLayout();
          lay.next(workArea);
        
    }//GEN-LAST:event_PatientbtnActionPerformed

    private void btnHospLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospLoginActionPerformed
        // TODO add your handling code here:
        HospLoginPanel hosLog = new HospLoginPanel(workArea, person, ptDirectory, docDirectory,hospDirectory, commDirectory, sys);
        workArea.add("HospLoginPanel",hosLog );
        CardLayout lay = (CardLayout) workArea.getLayout();
        lay.next(workArea);
    }//GEN-LAST:event_btnHospLoginActionPerformed

    private void btnCommLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommLoginActionPerformed
        // TODO add your handling code here:
        CommLoginPanel comLog = new CommLoginPanel(workArea, person, ptDirectory, docDirectory,hospDirectory, commDirectory, sys);
        workArea.add("CommLoginPanel",comLog );
        CardLayout lay = (CardLayout) workArea.getLayout();
        lay.next(workArea);
    }//GEN-LAST:event_btnCommLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Doctorbtn;
    private javax.swing.JButton Patientbtn;
    private javax.swing.JButton Systembtn;
    private javax.swing.JButton btnCommLogin;
    private javax.swing.JButton btnHospLogin;
    private javax.swing.JPanel controlArea;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
